### ISSUE TITLE
[RFC] Consider processing the catalog queue inside uuidToPhysicalPath

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.app.uuid#15]
Before #11 the function ``uuidToPhysicalPath`` used to fire a catalog search to return its result.
The catalog search was triggering the catalog queue processor to (re)index the objects in the queue.

That means that right after an object is created or moved, it might happen that it is not yet in the catalog or it is in the catalog with a wrong path.

I discovered this porting some code to Plone 6.

To adjust the code for Plone 6 I had to trigger the call to the ``processQueue`` function myself, e.g.:
```python
from Products.CMFCore.indexing import processQueue
...
        processQueue()
        path = uuidToPhysicalPath(uid)
        # or
        obj = uuidToObject(uuid)
```

Theoretically it is possible to add that call inside the ``uuidToPhysicalPath`` function, but I am not even sure I want to change this behavior myself :)

I just opened this issue to provide a fix (or upgrade path) to other people and to see what other people think about that.

**Comment by mauritsvanrees** [comment]
Such a change would make sense to me.
I did not consider this when making the initial change. I hope the performance gain is not completely undone, but I expect it should still be a lot faster than the original.

I you decide to work on this, please run the tests like this:

    PLONE_APP_UUID_TEST_SPEED_TOTAL=1000 bin/test -s plone.app.uuid

A lower number is fine too. This does a speed test with more documents (default is 40) and it will report on the speed:

```
Creating 1000 documents...
Time taken to create 1000 items: 49.97422194480896
Time taken for uuidToPhysicalPath: 0.010107040405273438
Time taken for uuidToURL: 0.36327505111694336
Time taken for uuidToObject: 0.24042797088623047
Time taken for uuidToCatalogBrain: 0.25431013107299805
```

If you take a before and after snapshot and compare them, we can easily see if there is a severe impact and then we might need to reconsider. But I don't expect this.

**Comment by mauritsvanrees** [comment]
It would need to be fixed in all places that call `_catalog()`. If I see it correctly: `uuidToPhysicalPath` and `uuidToCatalogBrain`.

**Comment by ale-rt** [comment]
`uuidToCatalogBrain` seems fine to me because it calls `.unrestrictedSearchResults` and that should trigger already the `processQueue` function:
https://github.com/plone/plone.app.uuid/blob/18c95506d165581ac556a9e844c841e6e3f72257/plone/app/uuid/utils.py#L108

**Comment by davisagli** [comment]
@mauritsvanrees I expect the performance gain will still be there in the cases where there are not pending index operations in the queue.
